name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "6 20 * * 6"

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true # 'bundle install' and cache
      - name: Check code style
        run: bundle exec rake rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5.0"
          - "2.5"
          - "2.6.0"
          - "2.6"
          - "2.7.0"
          - "2.7"
          - "3.0.0"
          - "3.0"
          - "3.1.0"
          - "3.1"
          - ruby-head
          - jruby-9.2
          - jruby-9.3
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache
      - name: Run tests
        run: bundle exec rake spec
